- name: Install Java and nc packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - "{{ java.yum_package }}"
    - nc

- name: Generate /tmp/id_rsa host key pair
  connection: local
  openssh_keypair:
    path: /tmp/id_rsa
    force: True

- name: Append to authorized_keys
  lineinfile:
    path: /home/centos/.ssh/authorized_keys
    insertafter: last
    line: "{{lookup('file', '/tmp/id_rsa.pub')}}"

- name: Copy private key to all servers
  copy:
    src: "/tmp/id_rsa"
    dest: "/home/centos/.ssh/id_rsa"
    owner: centos
    group: centos
    mode: '0600'